import os
import nbformat as nbf
from pathlib import Path

def create_notebook(filename, cells):
    nb = nbf.v4.new_notebook()
    nb.cells = cells
    with open(filename, 'w') as f:
        nbf.write(nb, f)
    print(f"Created {filename}")

def decision_note(step, chosen, why_works, alt_a, alt_a_pros, alt_a_cons, alt_b, alt_b_pros, alt_b_cons, reason):
    return f"""> **📌 Decision Note — Why {step}?**
>
> **Chosen approach:** {chosen}
>
> **Why this works:** {why_works}
>
> **Alternatives we could have used:**
> | Option | Pros | Cons |
> |--------|------|------|
> | {alt_a} | {alt_a_pros} | {alt_a_cons} |
> | {alt_b} | {alt_b_pros} | {alt_b_cons} |
>
> **Why we chose this over alternatives:** {reason}"""

def generate_notebooks():
    out_dir = Path("datasets/04_topic_modeling_news/notebooks")
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1. EDA and Preprocessing
    cells_01 = [
        nbf.v4.new_markdown_cell("# 01. EDA & Topic Modeling Preprocessing\n\n**Goal:** Explore the sampled dataset and apply aggressive text cleaning (Stopword removal + Lemmatization). Topic modeling is highly sensitive to noise!"),
        nbf.v4.new_code_cell("import pandas as pd\nimport sys\nimport nltk\nsys.path.append('../../../shared')\nfrom text_utils import clean_text_basic, remove_stopwords, apply_lemmatization"),
        nbf.v4.new_markdown_cell("## 1. Load Data"),
        nbf.v4.new_code_cell("df = pd.read_csv('../data/raw/dataset.csv')\nprint(df.head())\nprint(f'Total headlines: {len(df)}')"),
        nbf.v4.new_markdown_cell("## 2. Aggressive Cleaning"),
        nbf.v4.new_markdown_cell(decision_note(
            "Topic Modeling Preprocessing",
            "Stopword Removal + Lemmatization + Dropping short words",
            "Topic models group words that co-occur frequently. Stopwords ('the', 'and') and unlemmatized variants ('running', 'runs') will dominate the topics with useless noise if not handled.",
            "Basic Cleaning Only", "Fastest approach", "Topics will just be filled with 'to', 'of', 'in'.",
            "Stemming", "Reduces vocabulary", "Creates non-words (e.g. 'police' -> 'polic'), making the final extracted topics hard for humans to read.",
            "For unsupervised learning where the output must be human-interpretable, Lemmatization is strongly preferred over Stemming."
        )),
        nbf.v4.new_code_cell("from nltk.corpus import stopwords\nimport nltk\ntry:\n    nltk.data.find('corpora/stopwords')\nexcept LookupError:\n    nltk.download('stopwords', quiet=True)\nstop_words_set = set(stopwords.words('english'))\n\ndef aggressive_clean(text):\n    # Basic cleaning\n    text = clean_text_basic(text)\n    # Tokenize and remove stopwords\n    from nltk.tokenize import word_tokenize\n    tokens = word_tokenize(text)\n    tokens = remove_stopwords(tokens, stop_words_set)\n    # Keep only words with length >= 3 to filter out noise\n    tokens = [t for t in tokens if len(t) > 2]\n    return ' '.join(tokens)\n\ndf['cleaned'] = df['headline_text'].apply(aggressive_clean)\ndf['lemmatized'] = df['cleaned'].apply(apply_lemmatization)\ndf[['headline_text', 'lemmatized']].head(10)"),
        nbf.v4.new_code_cell("df.to_csv('../data/processed/processed_headlines.csv', index=False)\nprint('Saved processed data.')")
    ]
    create_notebook(out_dir / "01_eda_and_preprocessing.ipynb", cells_01)

    # 2. Latent Dirichlet Allocation (LDA)
    cells_02 = [
        nbf.v4.new_markdown_cell("# 02. Latent Dirichlet Allocation (LDA)\n\n**Goal:** Train an LDA model to discover 10 hidden topics in the news headlines using raw counts (Bag of Words)."),
        nbf.v4.new_code_cell("import pandas as pd\nimport joblib\nfrom sklearn.feature_extraction.text import CountVectorizer\nfrom sklearn.decomposition import LatentDirichletAllocation"),
        nbf.v4.new_markdown_cell("## 1. Load Data"),
        nbf.v4.new_code_cell("df = pd.read_csv('../data/processed/processed_headlines.csv')\ndf = df.dropna(subset=['lemmatized'])"),
        nbf.v4.new_markdown_cell(decision_note(
            "Vectorization for LDA",
            "CountVectorizer (Bag of Words)",
            "LDA is a probabilistic graphical model that assumes documents are generated by drawing topics, and then drawing words from those topics based on counts.",
            "TF-IDF Vectorizer", "Downweights common words natively", "LDA's statistical assumptions are fundamentally based on discrete integer counts, not continuous TF-IDF scores.",
            "Word Embeddings", "Captures deep semantic meaning", "LDA cannot process dense embeddings. Requires entirely different architectures (like Top2Vec or BERTopic).",
            "Mathematical compatibility dictates that standard LDA must use raw word counts."
        )),
        nbf.v4.new_markdown_cell("## 2. Vectorization"),
        nbf.v4.new_code_cell("tf_vectorizer = CountVectorizer(max_df=0.95, min_df=2, max_features=5000)\ntf = tf_vectorizer.fit_transform(df['lemmatized'])\ntf_feature_names = tf_vectorizer.get_feature_names_out()"),
        nbf.v4.new_markdown_cell("## 3. Fit LDA Model"),
        nbf.v4.new_code_cell("lda = LatentDirichletAllocation(n_components=10, random_state=42, learning_method='online')\nlda.fit(tf)"),
        nbf.v4.new_markdown_cell("## 4. Extract and Display Topics"),
        nbf.v4.new_code_cell("def display_topics(model, feature_names, no_top_words):\n    for topic_idx, topic in enumerate(model.components_):\n        print(f'Topic {topic_idx}:')\n        print(' '.join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))\n\ndisplay_topics(lda, tf_feature_names, 10)"),
        nbf.v4.new_code_cell("joblib.dump(lda, '../models/lda_model.pkl')")
    ]
    create_notebook(out_dir / "02_lda_topic_modeling.ipynb", cells_02)

    # 3. Non-Negative Matrix Factorization (NMF)
    cells_03 = [
        nbf.v4.new_markdown_cell("# 03. Non-Negative Matrix Factorization (NMF)\n\n**Goal:** Train an NMF model using TF-IDF and compare the generated topics to LDA. NMF often performs exceptionally well on short texts like headlines."),
        nbf.v4.new_code_cell("import pandas as pd\nimport joblib\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.decomposition import NMF"),
        nbf.v4.new_markdown_cell("## 1. Load Data"),
        nbf.v4.new_code_cell("df = pd.read_csv('../data/processed/processed_headlines.csv')\ndf = df.dropna(subset=['lemmatized'])"),
        nbf.v4.new_markdown_cell(decision_note(
            "Vectorization for NMF",
            "TfidfVectorizer",
            "NMF operates via linear algebra (matrix decomposition), not probability. It factorizes the TF-IDF matrix into two lower-dimensional matrices (Topics and Weights).",
            "CountVectorizer", "Simple", "Doesn't downweight overly common words, causing NMF topics to be noisy.",
            "LDA", "Standard statistical approach", "LDA often struggles with extremely short texts (like 5-word headlines) because there isn't enough word co-occurrence within a single document.",
            "NMF paired with TF-IDF is practically the industry standard for extracting topics from short texts (Headlines, Tweets)."
        )),
        nbf.v4.new_markdown_cell("## 2. TF-IDF Vectorization"),
        nbf.v4.new_code_cell("tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, max_features=5000)\ntfidf = tfidf_vectorizer.fit_transform(df['lemmatized'])\ntfidf_feature_names = tfidf_vectorizer.get_feature_names_out()"),
        nbf.v4.new_markdown_cell("## 3. Fit NMF Model"),
        nbf.v4.new_code_cell("nmf = NMF(n_components=10, random_state=42, init='nndsvd')\nnmf.fit(tfidf)"),
        nbf.v4.new_markdown_cell("## 4. Extract and Display Topics"),
        nbf.v4.new_code_cell("def display_topics(model, feature_names, no_top_words):\n    for topic_idx, topic in enumerate(model.components_):\n        print(f'Topic {topic_idx}:')\n        print(' '.join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))\n\ndisplay_topics(nmf, tfidf_feature_names, 10)"),
        nbf.v4.new_code_cell("joblib.dump(nmf, '../models/nmf_model.pkl')\njoblib.dump(tfidf_vectorizer, '../models/tfidf_vectorizer.pkl')"),
        nbf.v4.new_markdown_cell("## Key Takeaways\n- [x] Compare these topics to the LDA topics. You will generally find NMF topics on short headlines to be more coherent and distinct!")
    ]
    create_notebook(out_dir / "03_nmf_topic_modeling.ipynb", cells_03)

if __name__ == "__main__":
    generate_notebooks()
